[bot]
token = "..."

[logging]
dirs = "info,tg_bot_template::application::user::interactors=warn"

[database]
user = "..."
password = "..."
host = "tg_bot_template.postgres"
port = 5432
database = "api"
